### ISSUE TITLE
Landing - CTA form and button for subscription

### ISSUE THREAD

**Issue by marnovo** [src-d/backlog#604]
*Epic: "As a visitor to the source{d} landing page, I want to be able to subscribe to updates on what source{d} is bulding so that I can benefit from their upcoming products"*

Description of feature (please refer to mockups provided by @marnovo and @tiagopregueiro):
- Visitor comes to the landing page.
- Visitor gets interested in what we are doing after reading our main page.
- Visitor sees a CTA (click through action) form just beneath the landing page hero banner.
- The form has a sample youremail@domain.com example shaded in grey, that vanishes when focused by the user, shows up again when unfocused.
- Visitor types his email and clicks the button to subscribe to updates.
- Email is checked for format validation, like "x@y.z".
    - If validation successful, form border is highlighted in bright blue.
    - If validation is unsuccessful, form border is highlighted in red and a error messsage asking the user to retype his email is shown beneath the form.
- When clicking the button form data is sent to MailChimp platform via their API to the "Product Waiting List". Then, one of the three situations below happens:
    - If sending is successful, user was not in the list: form vanishes smoothly and updates to a "checked" icon plus a confirmation message telling him that he's registered but has to confirm subscription on his email.
    - If sending is successful, but user is already in the list: form vanishes smoothly and updates to a "checked" icon plus a confirmation message telling him that he was already registered and doesn't need to confirm subscription on his email.
    - If sending is unsuccessful, form vanishes smoothly and updates to a "error" icon plus a message telling him that he there was a problem sending the form and that he can either reload the page and try again <link to reload> or email us directly at hello@sourced.tech <link to email with subject set to "Product Waiting List Opt-in">.
- If possible (highly wanted), make the code flexible/self contained in a way we can reuse its structure in other pages of the website or in the Blog, with minor changes.
- The hidden field to be passed together with this on the landing page is `landinghero` (see API integration issue at #606).

**Comment by Serabe** [comment]
Given the new landing is coming, shall we drop this issue?
