### ISSUE TITLE
Landing/Blog - MailChimp integration

### ISSUE THREAD

**Issue by marnovo** [src-d/backlog#606]
*Epic: "Integrate the subscription forms to MailChimp platform via API"*

- Integrate our landing page and blog to MailChimp platform via their API to enable us to create forms for subscription/waiting lists.
- Form appearance should be customizable by us for each form.
- Target email list inside MailChimp should be customizable by us for each form.
- Check for contingency plans/caching for later submitting in case connection to MailChimp doesn't work.
- Current MailChimp account under marcelo@sourced.tech email (if necessary). 
- API documentation link: http://developer.mailchimp.com/documentation/mailchimp/
- API key `ec46ee8a505226ab9bc572189311b9c6-us15`.
- List id for the product update subscription list: `cdc443963b`.
- Will have a unique hidden field for each of the forms, to know where the subscription came. Mode details at: http://kb.mailchimp.com/lists/signup-forms/determine-webpage-signup-location

**Comment by Serabe** [comment]
Given the new landing is on its way, should we drop this issue?
